src/objects/Candidate__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>250</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <label>Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Work_Experience__c</fullName>
        <label>Work Experience</label>
        <length>250</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Candidate</label>
    <nameField>
        <label>Candidate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Job_Application__c.object
<CustomObject>
    <fields>
        <fullName>Candidate_Id__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Candidate Id</label>
        <referenceTo>Candidate__c</referenceTo>
        <relationshipLabel>Job_Applications</relationshipLabel>
        <relationshipName>Job_Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Position_Id__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Position Id</label>
        <referenceTo>Position__c</referenceTo>
        <relationshipLabel>Job Applications</relationshipLabel>
        <relationshipName>Job_Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Job Application</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Job Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Position__c.object
<CustomObject>
    <fields>
        <fullName>Description_Position__c</fullName>
        <label>Description Position</label>
        <length>250</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Education__c</fullName>
        <label>Education</label>
        <length>250</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Salary__c</fullName>
        <label>Salary</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Skills__c</fullName>
        <label>Skills</label>
        <required>true</required>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Good communication</fullName>
                </value>
                <value>
                    <fullName>Highly motiiveted</fullName>
                </value>
                <value>
                    <fullName>Analytical approach</fullName>
                </value>
                <value>
                    <fullName>Ability to learn non-stop</fullName>
                </value>
                <value>
                    <fullName>The ability to learn concepts and apply them to other problems</fullName>
                </value>
                <value>
                    <fullName>Basic mathematical skills</fullName>
                </value>
                <value>
                    <fullName>A passion for problem solving</fullName>
                </value>
                <value>
                    <fullName>Good writing skills</fullName>
                </value>
                <value>
                    <fullName>Confidence around a computer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Close</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Position</label>
    <nameField>
        <label>Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/MyController.cls
public class MyController {

	public ApexPages.StandardSetController setJob {
		get {
			setJob = new ApexPages.StandardSetController(Database.getQueryLocator(

					[SELECT Id, Candidate_Id__c, Candidate_Id__r.Phone_Number__c, Candidate_Id__r.Email__c, Candidate_Id__r.Work_Experience__c, Candidate_Id__r.Name, Candidate_Id__r.Last_Name__c,
					Position_Id__c, Position_Id__r.Name, Position_Id__r.Salary__c, Position_Id__r.Education__c, Position_Id__r.Description_Position__c, Position_Id__r.Skills__c, Position_Id__r.Status__c FROM Job_Application__c]));
			return setJob;
		}
		set;
	}

	public List<Job_Application__c> getJobApplication() {
		return (List<Job_Application__c>) setJob.getRecords();
	}
}